#macro SONIC_DEFAULT_GROUND_SKILL SONIC_GROUND_SKILL.NONE
#macro SONIC_DEFAULT_JUMP_SKILL SONIC_AIR_SKILL.NONE
#macro SONIC_DEFAULT_AUX_SKILL SONIC_AIR_SKILL.NONE
#macro SONIC_DEFAULT_SLAM_SKILL SONIC_SLAM_SKILL.NONE
#macro SONIC_DEFAULT_HOMING_ATTACK SONIC_HOMING_ATTACK.NONE
#macro SONIC_DEFAULT_PEEL_OUT false
#macro SONIC_DEFAULT_SHIELD_ACTIONS false

enum SONIC_GROUND_SKILL
{
    NONE,
    SKID_ATTACK,
    HAMMER_ATTACK
}

enum SONIC_AIR_SKILL
{
    NONE,
    INSTA_SHIELD,
    AIR_DASH,
    DROP_DASH
}

enum SONIC_SLAM_SKILL
{
    NONE,
    BOUND,
    STOMP
}

enum SONIC_HOMING_ATTACK
{
    NONE,
    ADVENTURE,
    RUSH,
    UNLEASHED,
    FRONTIERS,
    GENERATIONS
}