// Constants
#macro CONFIG_DATABASE global.config_database

#macro CONFIG_DEFAULT_HUD CONFIG_HUD.NONE
#macro CONFIG_DEFAULT_STATUS_BAR CONFIG_STATUS_BAR.ALL
#macro CONFIG_DEFAULT_ITEM_FEED true 
#macro CONFIG_DEFAULT_FLICKER CONFIG_FLICKER.OFF

#macro CONFIG_DEFAULT_LIVES true
#macro CONFIG_DEFAULT_TIME_OVER true
#macro CONFIG_DEFAULT_DEBUFFS true
#macro CONFIG_DEFAULT_BOOST_MODE true
#macro CONFIG_DEFAULT_TRICK_ACTIONS true
#macro CONFIG_DEFAULT_TAG_ACTIONS true
#macro CONFIG_DEFAULT_SWAP true

#macro CONFIG_DEFAULT_AERIAL_MASTERY true
#macro CONFIG_DEFAULT_FLIGHT_STYLE CONFIG_FLIGHT_STYLE.CLASSIC
#macro CONFIG_DEFAULT_FLIGHT_ASSIST true

enum CONFIG_HUD
{
    NONE = -1,
    CLUSTER,
    ADVENTURE,
    ADVENTURE_2,
    ADVANCE_2,
    ADVANCE_3,
    EPISODE_II
}

enum CONFIG_STATUS_BAR
{
    OFF,
    ACTIVE,
    ALL
}

enum CONFIG_FLICKER
{
    OFF,
    ORIGINAL,
    VIRTUAL_CONSOLE,
    VIRTUAL_CONSOLE_ADVANCE_3
}

enum CONFIG_FLIGHT_STYLE
{
    CLASSIC,
    ADVENTURE
}

// Create
global.config_database = db_create();

// Visuals
db_write(CONFIG_DATABASE, CONFIG_DEFAULT_HUD, "hud");
db_write(CONFIG_DATABASE, CONFIG_DEFAULT_STATUS_BAR, "status_bar");
db_write(CONFIG_DATABASE, CONFIG_DEFAULT_ITEM_FEED, "item_feed");
db_write(CONFIG_DATABASE, CONFIG_DEFAULT_FLICKER, "flicker");

// Gameplay
db_write(CONFIG_DATABASE, CONFIG_DEFAULT_LIVES, "lives");
db_write(CONFIG_DATABASE, CONFIG_DEFAULT_TIME_OVER, "time_over");
db_write(CONFIG_DATABASE, CONFIG_DEFAULT_DEBUFFS, "debuffs");
db_write(CONFIG_DATABASE, CONFIG_DEFAULT_BOOST_MODE, "boost_mode");
db_write(CONFIG_DATABASE, CONFIG_DEFAULT_TRICK_ACTIONS, "trick_actions");
db_write(CONFIG_DATABASE, CONFIG_DEFAULT_TAG_ACTIONS, "tag_actions");
db_write(CONFIG_DATABASE, CONFIG_DEFAULT_SWAP, "swap");

// Controls
db_write(CONFIG_DATABASE, CONFIG_DEFAULT_AERIAL_MASTERY, "aerial_mastery");
db_write(CONFIG_DATABASE, CONFIG_DEFAULT_FLIGHT_STYLE, "flight_style");
db_write(CONFIG_DATABASE, CONFIG_DEFAULT_FLIGHT_ASSIST, "flight_assist");