#macro AERIAL_FLAG_PLATFORM 1
#macro AERIAL_FLAG_SHIELD_ACTION 2
#macro AERIAL_FLAG_BOUND 4
#macro AERIAL_FLAG_AIR_DASH 8
#macro AERIAL_FLAG_HAMMER 16

#macro LOOK_DURATION 120
#macro SLIDE_DURATION 30
#macro RECOVERY_DURATION 120
#macro SPRING_DURATION 16
#macro TRICK_LOCK_DURATION 9
#macro SWAP_DURATION 60 

#macro INVINCIBILITY_DURATION 1380
#macro SPEED_UP_DURATION 900
#macro DEBUFF_DURAION 600

#macro SLIDE_THRESHOLD 2.5
#macro ROLL_THRESHOLD 0.5

#macro CPU_RESPAWN_DURATION 300
#macro CPU_GAMEPAD_DURATION 600
#macro CPU_RECORD_COUNT 16

#macro ANIMATION_RECORD_COUNT 16
#macro AFTERIMAGE_COUNT 3
#macro SPEED_BREAK_COUNT 16

enum CHARACTER
{
    NONE = -1,
    SONIC,
    MILES,
    KNUCKLES,
    AMY,
    CREAM
}

enum PHASE
{ 
    ENTER,
    STEP,
    EXIT
}

enum TRICK
{
    UP,
    DOWN,
    FRONT,
    BACK
}

enum SHIELD
{
    NONE,
    BASIC,
    MAGNETIC,
    AQUA,
    FLAME,
    THUNDER
}

enum CPU_STATE
{
    FOLLOW,
    CROUCH,
    SPIN_DASH,
    FLIGHT_ASSIST
}

enum HEART_PATTERN
{
    HAMMER_ATTACK,
    DOUBLE_HAMMER_ATTACK,
    AIR_HAMMER_ATTACK,
    HAMMER_WHIRL
}