#macro HEART_COUNT 4

// Skill set
#macro AMY_DEFAULT_HAMMER_SKILL AMY_HAMMER_SKILL.HAMMER_ATTACK
#macro AMY_DEFAULT_HAMMER_WHIRL true
#macro AMY_DEFAULT_HAMMER_JUMP true
#macro AMY_DEFAULT_SPIN false
#macro AMY_DEFAULT_SPIN_ALT AMY_SPIN_ALT.LEAP
#macro AMY_DEFAULT_SHIELD_ACTIONS false 

enum AMY_HAMMER_SKILL
{
    HAMMER_ATTACK,
    DOUBLE_HAMMER_ATTACK,
    BIG_HAMMER_ATTACK
}

enum AMY_SPIN_ALT
{
    LEAP,
    DASH
}