#macro PROPELLER_FLIGHT_DURATION 480
#macro PROPELLER_FLIGHT_THRESHOLD -0.75

#macro MILES_DEFAULT_GROUND_SKILL MILES_GROUND_SKILL.NONE
#macro MILES_DEFAULT_FLIGHT_ASSIST true

enum MILES_GROUND_SKILL
{
    NONE,
    TAIL_SWIPE,
    TORNADO_ATTACK,
    HAMMER_ATTACK
}

enum MILES_FLIGHT_STYLE
{
    CLASSIC,
    ADVENTURE
}