#macro PROPELLER_FLIGHT_DURATION 480
#macro PROPELLER_FLIGHT_THRESHOLD -0.75

// Skill set
#macro MILES_DEFAULT_GROUND_SKILL MILES_GROUND_SKILL.NONE
#macro MILES_DEFAULT_FLIGHT_ASSIST true
#macro MILES_DEFAULT_INSTA_SHIELD false
#macro MILES_DEFAULT_SHIELD_ACTIONS false 

enum MILES_GROUND_SKILL
{
    NONE,
    TAIL_SWIPE,
    TORNADO_ATTACK,
    HAMMER_ATTACK
}

enum MILES_FLIGHT_STYLE
{
    CLASSIC,
    ADVENTURE
}